[files.assets.config]
target_dir="src/sotoki/assets"

[files.assets.actions."static/css/stacks.css"]
action="get_file"
target_dir="static/css"
target_file="stacks.css"
source="https://cdn.sstatic.net/Shared/stacks.css?v=ca5319e49c63"

[files.assets.actions."static/js/tex-mml-chtml.js"]
action="get_file"
target_dir="static/js"
target_file="tex-mml-chtml.js"
source="https://cdn.jsdelivr.net/npm/mathjax@3.1.3/es5/tex-mml-chtml.js"

[files.assets.actions."static/js/stack-icons.js"]
action="get_file"
target_dir="static/js"
target_file="stack-icons.js"
source="https://unpkg.com/@stackoverflow/stacks-icons@2.20.0/build/index.js"

[files.assets.actions."static/js/moment.min.js"]
action="get_file"
target_dir="static/js"
target_file="moment.min.js"
source="https://momentjs.com/downloads/moment.min.js"

[files.assets.actions."static/js/jdenticon.min.js"]
action="get_file"
target_dir="static/js"
target_file="jdenticon.min.js"
source="https://raw.githubusercontent.com/dmester/jdenticon/3.3.0/dist/jdenticon.min.js"

[files.assets.actions."static/css/highlight.default.min.css"]
action="get_file"
target_dir="static/css"
target_file="highlight.default.min.css"
source="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/styles/default.min.css"

[files.assets.actions."static/js/highlight.min.js"]
action="get_file"
target_dir="static/js"
target_file="highlight.min.js"
source="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/highlight.min.js"

[files.assets.actions."static/js/webp-hero.polyfill.js"]
action="get_file"
target_dir="static/js"
target_file="webp-hero.polyfill.js"
source="https://unpkg.com/webp-hero@0.0.0-dev.27/dist-cjs/polyfills.js"

[files.assets.actions."static/js/webp-hero.bundle.js"]
action="get_file"
target_dir="static/js"
target_file="webp-hero.bundle.js"
source="https://unpkg.com/webp-hero@0.0.0-dev.27/dist-cjs/webp-hero.bundle.js"

[files.assets.actions."static/js/webp-handler.js"]
action="get_file"
target_dir="static/js"
target_file="webp-handler.js"
source="https://gist.githubusercontent.com/rgaudin/60bb9cc6f187add506584258028b8ee1/raw/9d575b8e25d67eed2a9c9a91d3e053a0062d2fc7/web-handler.js"

[files.assets.actions."static/js/MathJax.js"]
action="get_file"
target_dir="static/js"
target_file="MathJax.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML-full"

[files.assets.actions."static/js/config/TeX-AMS_HTML-full.js"]
action="get_file"
target_dir="static/js/config"
target_file="TeX-AMS_HTML-full.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS_HTML-full.js?V=2.7.5"

[files.assets.actions."static/js/extensions/MathMenu.js"]
action="get_file"
target_dir="static/js/extensions"
target_file="MathMenu.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/extensions/MathMenu.js?V=2.7.5"

[files.assets.actions."static/js/extensions/MathZoom.js"]
action="get_file"
target_dir="static/js/extensions"
target_file="MathZoom.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/extensions/MathZoom.js?V=2.7.5"

[files.assets.actions."static/js/extensions/TeX/begingroup.js"]
action="get_file"
target_dir="static/js/extensions/TeX"
target_file="begingroup.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/extensions/TeX/begingroup.js?V=2.7.5"

[files.assets.actions."static/js/jax/output/HTML-CSS/fonts/STIX/fontdata.js"]
action="get_file"
target_dir="static/js/jax/output/HTML-CSS/fonts/STIX"
target_file="fontdata.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/output/HTML-CSS/fonts/STIX/fontdata.js?V=2.7.5"

[files.assets.actions."static/js/jax/element/mml/optable/BasicLatin.js"]
action="get_file"
target_dir="static/js/jax/element/mml/optable"
target_file="BasicLatin.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/element/mml/optable/BasicLatin.js?V=2.7.5"

[files.assets.actions."static/js/jax/output/HTML-CSS/fonts/STIX/General/Italic/MathItalic.js"]
action="get_file"
target_dir="static/js/jax/output/HTML-CSS/fonts/STIX/General/Italic"
target_file="MathItalic.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/output/HTML-CSS/fonts/STIX/General/Italic/MathItalic.js?V=2.7.5"

[files.assets.actions."static/js/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathItalic.js"]
action="get_file"
target_dir="static/js/jax/output/HTML-CSS/fonts/STIX/General/Regular"
target_file="MathItalic.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathItalic.js?V=2.7.5"

[files.assets.actions."static/js/jax/output/HTML-CSS/fonts/STIX/General/Italic/GreekItalic.js"]
action="get_file"
target_dir="static/js/jax/output/HTML-CSS/fonts/STIX/General/Italic"
target_file="GreekItalic.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/output/HTML-CSS/fonts/STIX/General/Italic/GreekItalic.js?V=2.7.5"

[files.assets.actions."static/js/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekItalic.js"]
action="get_file"
target_dir="static/js/jax/output/HTML-CSS/fonts/STIX/General/Regular"
target_file="GreekItalic.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekItalic.js?V=2.7.5"

[files.assets.actions."static/js/jax/output/HTML-CSS/fonts/TeX/fontdata.js"]
action="get_file"
target_dir="static/js/jax/output/HTML-CSS/fonts/TeX"
target_file="fontdata.js"
source="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/jax/output/HTML-CSS/fonts/TeX/fontdata.js?V=2.7.5"

[files.assets.actions."Img/forms/icon-disabled.svg"]
action="get_file"
target_dir="Img/forms"
target_file="icon-disabled.svg"
source="https://cdn.sstatic.net/Img/forms/icon-disabled.svg"

[files.assets.actions."Img/forms/icon-warning.svg"]
action="get_file"
target_dir="Img/forms"
target_file="icon-warning.svg"
source="https://cdn.sstatic.net/Img/forms/icon-warning.svg"

[files.assets.actions."Img/forms/icon-error.svg"]
action="get_file"
target_dir="Img/forms"
target_file="icon-error.svg"
source="https://cdn.sstatic.net/Img/forms/icon-error.svg"

[files.assets.actions."Img/forms/icon-success.svg"]
action="get_file"
target_dir="Img/forms"
target_file="icon-success.svg"
source="https://cdn.sstatic.net/Img/forms/icon-success.svg"

[files.assets.actions."Img/hero/anonymousHeroBackground.svg"]
action="get_file"
target_dir="Img/hero"
target_file="anonymousHeroBackground.svg"
source="https://cdn.sstatic.net/Img/hero/anonymousHeroBackground.svg"

[files.assets.actions."Img/img-upload.png"]
action="get_file"
target_dir="Img"
target_file="img-upload.png"
source="https://cdn.sstatic.net/Img/img-upload.png"

[files.assets.actions."Img/unified/sprites.png"]
action="get_file"
target_dir="Img/unified"
target_file="sprites.png"
source="https://cdn.sstatic.net/Img/unified/sprites.png"

[files.assets.actions."Img/unified/sprites.svg"]
action="get_file"
target_dir="Img/unified"
target_file="sprites.svg"
source="https://cdn.sstatic.net/Img/unified/sprites.svg"

[files.assets.actions."Img/unifiedmeta/sprites.png"]
action="get_file"
target_dir="Img/unifiedmeta"
target_file="sprites.png"
source="https://cdn.sstatic.net/Img/unifiedmeta/sprites.png"

[files.assets.actions."Img/unified/wmd-buttons.svg"]
action="get_file"
target_dir="Img/unified"
target_file="wmd-buttons.svg"
source="https://cdn.sstatic.net/Img/unified/wmd-buttons.svg"

[files.assets.actions."Img/unified/wmd-buttons-dark.svg"]
action="get_file"
target_dir="Img/unified"
target_file="wmd-buttons-dark.svg"
source="https://cdn.sstatic.net/Img/unified/wmd-buttons-dark.svg"

[files.assets.actions."Img/progress-dots.gif"]
action="get_file"
target_dir="Img"
target_file="progress-dots.gif"
source="https://cdn.sstatic.net/Img/progress-dots.gif"

[files.assets.actions."Img/share-sprite.png"]
action="get_file"
target_dir="Img"
target_file="share-sprite.png"
source="https://cdn.sstatic.net/Img/share-sprite.png"

[files.assets.actions."Img/unifiedmeta/sprites.svg"]
action="get_file"
target_dir="Img/unifiedmeta"
target_file="sprites.svg"
source="https://cdn.sstatic.net/Img/unifiedmeta/sprites.svg"

[files.assets.actions."Img/developer-story/timeline.svg"]
action="get_file"
target_dir="Img/developer-story"
target_file="timeline.svg"
source="https://cdn.sstatic.net/Img/developer-story/timeline.svg"

[files.assets.actions."Img/user-profile-sprite.png"]
action="get_file"
target_dir="Img"
target_file="user-profile-sprite.png"
source="https://cdn.sstatic.net/Img/user-profile-sprite.png"

[files.assets.actions."Img/user-profile-sprite.svg"]
action="get_file"
target_dir="Img"
target_file="user-profile-sprite.svg"
source="https://cdn.sstatic.net/Img/user-profile-sprite.svg"

[files.assets.actions."Img/share-sprite-new.png"]
action="get_file"
target_dir="Img"
target_file="share-sprite-new.png"
source="https://cdn.sstatic.net/Img/share-sprite-new.png"

[files.assets.actions."Img/share-sprite-new.svg"]
action="get_file"
target_dir="Img"
target_file="share-sprite-new.svg"
source="https://cdn.sstatic.net/Img/share-sprite-new.svg"

[files.assets.actions."Img/favicons-sprite16.png"]
action="get_file"
target_dir="Img"
target_file="favicons-sprite16.png"
source="https://cdn.sstatic.net/Img/favicons-sprite16.png"

[files.assets.actions."Img/favicons-sprite16-dark.png"]
action="get_file"
target_dir="Img"
target_file="favicons-sprite16-dark.png"
source="https://cdn.sstatic.net/Img/favicons-sprite16-dark.png"

[files.assets.actions."Img/favicons-sprite32.png"]
action="get_file"
target_dir="Img"
target_file="favicons-sprite32.png"
source="https://cdn.sstatic.net/Img/favicons-sprite32.png"

[files.assets.actions."Img/favicons-sprite32-dark.png"]
action="get_file"
target_dir="Img"
target_file="favicons-sprite32-dark.png"
source="https://cdn.sstatic.net/Img/favicons-sprite32-dark.png"

[files.assets.actions."Img/filter-sprites.png"]
action="get_file"
target_dir="Img"
target_file="filter-sprites.png"
source="https://cdn.sstatic.net/Img/filter-sprites.png"

[files.assets.actions."Img/filter-sprites.svg"]
action="get_file"
target_dir="Img"
target_file="filter-sprites.svg"
source="https://cdn.sstatic.net/Img/filter-sprites.svg"

[files.assets.actions."Img/img-upload.svg"]
action="get_file"
target_dir="Img"
target_file="img-upload.svg"
source="https://cdn.sstatic.net/Img/img-upload.svg"

[files.assets.actions."Img/user.svg"]
action="get_file"
target_dir="Img"
target_file="user.svg"
source="https://cdn.sstatic.net/Img/user.svg"

[files.assets.actions."Img/fatarrows.png"]
action="get_file"
target_dir="Img"
target_file="fatarrows.png"
source="https://cdn.sstatic.net/Img/fatarrows.png"

[files.assets.actions."Img/open-graph/checkmark.png"]
action="get_file"
target_dir="Img/open-graph"
target_file="checkmark.png"
source="https://cdn.sstatic.net/Img/open-graph/checkmark.png"
